src/objects/openCTIconfig__c.object
<CustomObject>
    <fields>
        <fullName>AccountName__c</fullName>
        <label>AccountName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>openCTIconfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContactName__c</fullName>
        <label>ContactName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>openCTIconfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Lightning CTI Config</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>openCTIconfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lightning CTI Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ctiApexController.cls
public with sharing class ctiApexController {
	public ctiApexController() {

	}

	@auraEnabled
	public Static List<Contact> getTheContacts(String searchTerm) {
		String srch = '%' + searchTerm + '%';
		return [SELECT Email,HomePhone,Id,MobilePhone,Name,Phone FROM Contact WHERE Name LIKE: srch];
	}

	@auraEnabled
	public Static String createMyTask(String myAccountId, String myContactId, String myDescription) {
		//System.debug('coshea : ' + myDuration);
		//Integer myInt = Integer.valueOf(myDuration);

		Task tsk = new Task();
		tsk.WhoId = myContactId;
		tsk.CallDisposition = 'Internal';
		tsk.CallObject = 'DemoCall';
		tsk.Subject = 'Call Log';
		tsk.Priority = 'Normal';
		tsk.Description = myDescription;
		//tsk.CallDurationInSeconds = myInt;
		tsk.Type = 'Call';
		tsk.CallType = 'Inbound';
		tsk.WhatId = myAccountId;
		insert tsk;

		return tsk.Id;
	}

	@auraEnabled
	public Static openCTIconfig__c getMyConfig() {
		return [SELECT AccountName__c,Account__c,ContactName__c,Contact__c,Id,isActive__c,Phone__c,Title__c FROM openCTIconfig__c WHERE isActive__c=true LIMIT 1];
	}
}